typography_spectrum: 0.9063020262401551
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.518473394215107
  lightness: 0.13966108998283744
  saturation: 0.003979790490120649
  rhythmicContrast: 0.5685790320858359
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.02045970014296472
analytics:
  google: null
  facebook: null
  twitter: null
name: Planted Landscape
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Planted Landscape
purpose: []
