name: Planted Landscape
favicon: null
layout_spectrum: 0
typography_spectrum: 0.51177
title: Planted Landscape
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9cb2ef'
    - '#779344'
    - '#d9c7c5'
    - '#030b00'
    - '#393824'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
